## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: false

# log default is ERROR, but WARN is more helpful
log:
  level: WARN
  # level: INFO

# enable dashboard on 8080 with NO AUTH
api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    exposedByDefault: true
    watch: true
  file:
    fileName: /etc/traefik/traefik.yaml
    watch: true

# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
  # websecure:
  #   address: :443

## DYNAMIC CONFIG
# Remove or comment out the TLS configuration to disable HTTPS
# tls:
#   certificates:
#     - certFile: /certs/local-cert.pem
#       keyFile: /certs/local-key.pem
#   options:
#     default:
#       sniStrict: true