name: Build Verification Test
run-name: Build Verification Test by ${{ github.actor }} ðŸš€
on:
  push:
    branches: [ 3.x-develop ]
  pull_request:
    branches: [ 3.x-develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Status report of software versions and variables
        run: |
          php -v
          composer --version
          npm -v
      - name: Conducting testing for the Composer build
        run: |
         composer validate
         composer outdated -D
      - name: Conducting testing for the Cypress build
        run: |
          cd cy && npm install
          npm audit || true